name: mobile_figure_pay_partner
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.17.0
  flutter_native_splash: ^1.2.1
  hooks_riverpod: ^0.14.0+4
  flutter_svg: ^0.22.0
  uni_links: ^0.5.1
  url_launcher: ^6.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_native_splash:
  background_image: "assets/bg_gradient.png"
  image: "assets/figure_pay_logo_long.png"
  fullscreen: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Custom
      fonts:
        - asset: fonts/FontAwesome/Custom.ttf
    - family: Overpass
      fonts:
        - asset: fonts/Overpass/Overpass-Black.ttf
          weight: 900
        - asset: fonts/Overpass/Overpass-ExtraBold.ttf
          weight: 800
        - asset: fonts/Overpass/Overpass-Bold.ttf
          weight: 700
        - asset: fonts/Overpass/Overpass-SemiBold.ttf
          weight: 600
        - asset: fonts/Overpass/Overpass-Regular.ttf
          weight: 400
        - asset: fonts/Overpass/Overpass-Light.ttf
          weight: 300
        - asset: fonts/Overpass/Overpass-ExtraLight.ttf
          weight: 200
        - asset: fonts/Overpass/Overpass-Thin.ttf
          weight: 100
          style: normal
    - family: Jura
      fonts:
        - asset: fonts/Jura/Jura-Bold.ttf
          weight: 700
        - asset: fonts/Jura/Jura-SemiBold.ttf
          weight: 600
        - asset: fonts/Jura/Jura-Medium.ttf
          weight: 500
        - asset: fonts/Jura/Jura-Regular.ttf
          weight: 400
        - asset: fonts/Jura/Jura-Light.ttf
          weight: 300
          style: normal
    - family: GothicA1
      fonts:
        - asset: fonts/GothicA1/GothicA1-Black.ttf
          weight: 900
        - asset: fonts/GothicA1/GothicA1-ExtraBold.ttf
          weight: 800
        - asset: fonts/GothicA1/GothicA1-Bold.ttf
          weight: 700
        - asset: fonts/GothicA1/GothicA1-SemiBold.ttf
          weight: 600
        - asset: fonts/GothicA1/GothicA1-Medium.ttf
          weight: 500
        - asset: fonts/GothicA1/GothicA1-Regular.ttf
          weight: 400
        - asset: fonts/GothicA1/GothicA1-Light.ttf
          weight: 300
        - asset: fonts/GothicA1/GothicA1-ExtraLight.ttf
          weight: 200
        - asset: fonts/GothicA1/GothicA1-Thin.ttf
          weight: 100
          style: normal
    - family: Poppins
      fonts:
        - asset: fonts/Poppins/Poppins-Black.ttf
          weight: 900
        - asset: fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins/Poppins-Regular.ttf
          weight: 400
          style: normal